#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.3.2 effective-5.10 (swiftlang-6.3.2.1.108 clang-2100.1.1.101)
#ifndef AUTOPAYSDKWITHOUTOCR_SWIFT_H
#define AUTOPAYSDKWITHOUTOCR_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif // defined(__OBJC__)
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  if __has_feature(generalized_swift_name)
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  else
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
#  endif
# else
#  define SWIFT_ENUM(_type, _name, _extensibility) _type _name; enum 
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM_TAG)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_TAG enum
# else
#  define SWIFT_ENUM_TAG
# endif
#endif
#if !defined(SWIFT_ENUM_FWD_DECL)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_FWD_DECL(_type, _name) enum _name : _type;
# else
#  define SWIFT_ENUM_FWD_DECL(_type, _name) typedef _type _name;
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_AVAILABILITY_DOMAIN)
# define SWIFT_AVAILABILITY_DOMAIN(dom, ...) __attribute__((availability(domain: dom, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if !__has_feature(nullability)
# define _Nonnull
# define _Nullable
# define _Null_unspecified
#elif !defined(__OBJC__)
# pragma clang diagnostic ignored "-Wnullability-extension"
#endif
#if !__has_feature(nullability_nullable_result)
# define _Nullable_result _Nullable
#endif
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="AutopaySdkWithoutOCR",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__cplusplus)
extern "C" {
#endif

#if defined(__cplusplus)
} // extern "C"
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import ObjectiveC;
@import UIKit;
@import WebKit;
#endif

#endif // defined(__OBJC__)
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="AutopaySdkWithoutOCR",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class NSCoder;
SWIFT_CLASS("_TtC20AutopaySdkWithoutOCR30APApplePayGatewayContainerView")
@interface APApplePayGatewayContainerView : UIView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

/// A customizable style container that defines the visual appearance and layout
/// for a grid of bank items within the SDK.
/// Use <code>APBankGridStyle</code> to configure how bank options are presented in grid form,
/// including the number of columns, cell dimensions, corner radius, and colors for
/// the background and borders in checked/unchecked states.
/// note:
/// Values provided here are defaults and can be overridden per usage..
/// Properties:
/// <ul>
///   <li>
///     <code>columns</code>: The number of columns in the grid. Defaults to <code>3</code>.
///   </li>
///   <li>
///     <code>cellHeight</code>: The fixed height for each grid cell, in points. Defaults to <code>80</code>.
///   </li>
///   <li>
///     <code>radius</code>: The corner radius applied to each grid cell, in points. Defaults to <code>12</code>.
///   </li>
///   <li>
///     <code>backgroundColor</code>: The background color for grid cells. Defaults to <code>light: #FFFFFF, dark: #0F0F0F</code>.
///   </li>
///   <li>
///     <code>checkedBorderColor</code>: The border color used when a cell is selected (checked).
///     Defaults to <code>light: #2E72BF, dark: #158EE6</code>.
///   </li>
///   <li>
///     <code>uncheckedBorderColor</code>: The border color used when a cell is not selected (unchecked).
///     Defaults to <code>light: #808080 alpha 0.4, dark: #CCCCCC alpha 0.4</code>.
///   </li>
/// </ul>
/// Example:
/// <ul>
///   <li>
///     Set <code>columns</code> to <code>4</code> for denser layouts.
///   </li>
///   <li>
///     Increase <code>cellHeight</code> for larger cell.
///   </li>
///   <li>
///     Adjust <code>radius</code> to align with your app’s corner style.
///   </li>
///   <li>
///     Provide custom colors to ensure contrast and accessibility.
///   </li>
/// </ul>
/// Thread-safety:
/// <ul>
///   <li>
///     This type is a simple configuration object and is not thread-safe by design.
///     Configure it on the main thread or before passing it to UI components.
///   </li>
/// </ul>
/// Accessibility:
/// <ul>
///   <li>
///     Ensure chosen colors provide sufficient contrast, especially for <code>checkedBorderColor</code>
///     and <code>uncheckedBorderColor</code>, to make selection states visually distinguishable.
///   </li>
/// </ul>
SWIFT_CLASS("_TtC20AutopaySdkWithoutOCR15APBankGridStyle")
@interface APBankGridStyle : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC20AutopaySdkWithoutOCR34APBankTransferGatewayContainerView")
@interface APBankTransferGatewayContainerView : UIView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

SWIFT_CLASS("_TtC20AutopaySdkWithoutOCR26APBlikGatewayContainerView")
@interface APBlikGatewayContainerView : UIView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

/// A customizable style container that defines the visual appearance
/// for button components within the SDK.
/// Use <code>APButtonStyle</code> to configure how buttons look in enabled and disabled states,
/// including container and border colors, text styles, optional icon tint, corner radius,
/// border width, and minimum height. You can create a fully custom instance or use
/// predefined presets via <code>APButtonStyleType</code> (e.g., primary, secondary, tertiary, paymentMethod).
/// note:
/// Values provided here act as defaults for a button configuration and can be
/// overridden where appropriate. Prefer using <code>APButtonStyleType</code> for standard appearances.
/// Properties:
/// <ul>
///   <li>
///     <code>containerColor</code>: Background color for the button when enabled.
///   </li>
///   <li>
///     <code>containerInactiveColor</code>: Background color for the button when disabled.
///   </li>
///   <li>
///     <code>borderColor</code>: Border color for the button when enabled.
///   </li>
///   <li>
///     <code>borderInactiveColor</code>: Border color for the button when disabled.
///   </li>
///   <li>
///     <code>textStyle</code>: Text style (font and color) for the enabled state.
///   </li>
///   <li>
///     <code>textInactiveStyle</code>: Text style (font and color) for the disabled state.
///   </li>
///   <li>
///     <code>iconColor</code>: Optional tint color for any icon displayed in the button.
///   </li>
///   <li>
///     <code>cornerRadius</code>: Corner radius applied to the button’s container. Use <code>.infinity</code> for a pill shape.
///   </li>
///   <li>
///     <code>borderWidth</code>: Width of the button’s border, in points.
///   </li>
///   <li>
///     <code>minHeight</code>: Minimum height of the button, in points.
///   </li>
/// </ul>
/// Example:
/// <ul>
///   <li>
///     Use <code>.init(style: .primary)</code> for high-emphasis actions.
///   </li>
///   <li>
///     Increase <code>cornerRadius</code> or set to <code>.infinity</code> for pill-shaped buttons.
///   </li>
///   <li>
///     Adjust <code>borderWidth</code> and <code>borderColor</code> for outlined buttons.
///   </li>
///   <li>
///     Provide distinct <code>textInactiveStyle</code> and <code>containerInactiveColor</code> to clarify disabled states.
///   </li>
/// </ul>
/// Thread-safety:
/// <ul>
///   <li>
///     This type is a simple configuration object and is not thread-safe by design.
///     Configure it on the main thread or before passing it to UI components.
///   </li>
/// </ul>
/// Accessibility:
/// <ul>
///   <li>
///     Ensure sufficient contrast between text and background in both enabled and disabled states.
///   </li>
///   <li>
///     Consider larger <code>minHeight</code> values to improve tap targets and ergonomics.
///   </li>
/// </ul>
SWIFT_CLASS("_TtC20AutopaySdkWithoutOCR13APButtonStyle")
@interface APButtonStyle : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC20AutopaySdkWithoutOCR36APCardActivationGatewayContainerView")
@interface APCardActivationGatewayContainerView : UIView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

SWIFT_CLASS("_TtC20AutopaySdkWithoutOCR26APCardGatewayContainerView")
@interface APCardGatewayContainerView : UIView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

/// A customizable style container that defines the visual appearance
/// for checkbox controls within the SDK.
/// Use <code>APCheckboxStyle</code> to configure the colors used to represent checked,
/// unchecked, and error states of a checkbox. This enables consistent, themeable
/// presentation of selection and validation status across the SDK.
/// note:
/// Values provided here are defaults and can be overridden per usage.
/// Properties:
/// <ul>
///   <li>
///     <code>checkedColor</code>: The color applied to the checkbox when it is selected (checked).
///     Defaults to <code>light: #2E72BF, dark: #158EE6</code>.
///   </li>
///   <li>
///     <code>uncheckedColor</code>: The color applied to the checkbox when it is not selected (unchecked).
///     Defaults to <code>light: #808080, dark: #CCCCCC</code>.
///   </li>
///   <li>
///     <code>errorColor</code>: The color applied to indicate an error state (e.g., validation failure).
///     Defaults to <code>light: #FF3B30, dark: #FF453A</code> (SDK error color).
///   </li>
/// </ul>
/// Example:
/// <ul>
///   <li>
///     Use a strong, brand-aligned <code>checkedColor</code> to highlight selection.
///   </li>
///   <li>
///     Choose a neutral <code>uncheckedColor</code> for a subtle, inactive look.
///   </li>
///   <li>
///     Ensure <code>errorColor</code> is attention-grabbing and clearly indicates invalid state.
///   </li>
/// </ul>
/// Thread-safety:
/// <ul>
///   <li>
///     This type is a simple configuration object and is not thread-safe by design.
///     Configure it on the main thread or before passing it to UI components.
///   </li>
/// </ul>
/// Accessibility:
/// <ul>
///   <li>
///     Ensure sufficient contrast for <code>checkedColor</code> and <code>uncheckedColor</code> against the background
///     so that selection states are visually distinguishable.
///   </li>
///   <li>
///     Choose an <code>errorColor</code> that is clearly recognizable and consistent with other error indicators.
///   </li>
/// </ul>
SWIFT_CLASS("_TtC20AutopaySdkWithoutOCR15APCheckboxStyle")
@interface APCheckboxStyle : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// A lightweight container that defines a paired color for Light and Dark appearances,
/// enabling consistent, appearance-aware color usage across the SDK.
/// Use <code>APColor</code> to provide a single token that contains both light and dark variants
/// of a SwiftUI <code>Color</code>. You can supply distinct values for each appearance or a single
/// color to be used in both modes.
/// Properties:
/// <ul>
///   <li>
///     <code>light</code>: The color used in Light Mode.
///   </li>
///   <li>
///     <code>dark</code>: The color used in Dark Mode.
///   </li>
/// </ul>
/// Example:
/// <ul>
///   <li>
///     Provide explicit light and dark variants:
///     <ul>
///       <li>
///         <code>APColor(light: Color(red: 0.2, green: 0.5, blue: 0.9), dark: Color(red: 0.1, green: 0.4, blue: 0.8))</code>
///       </li>
///     </ul>
///   </li>
///   <li>
///     Use a single color for both appearances:
///     <ul>
///       <li>
///         <code>APColor(light: .gray)</code>
///       </li>
///     </ul>
///   </li>
/// </ul>
/// Thread-safety:
/// <ul>
///   <li>
///     This type is immutable after initialization and thus safe to share across threads.
///   </li>
/// </ul>
/// Accessibility:
/// <ul>
///   <li>
///     Ensure that chosen <code>light</code> and <code>dark</code> variants provide sufficient contrast
///     in their respective appearances, especially when used for text, borders, or
///     interaction affordances.
///   </li>
/// </ul>
SWIFT_CLASS("_TtC20AutopaySdkWithoutOCR7APColor")
@interface APColor : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC20AutopaySdkWithoutOCR8APConfig")
@interface APConfig : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC20AutopaySdkWithoutOCR10APCurrency")
@interface APCurrency : NSObject
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC20AutopaySdkWithoutOCR13APCustomerFee")
@interface APCustomerFee : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// A customizable style container that defines the visual appearance
/// for Dynamic Currency Conversion (DCC) payment form options within the SDK.
/// Use <code>APDCCPaymentFormStyle</code> to configure how DCC options are presented,
/// including the corner radius, background color, and border colors for
/// selected and unselected states.
/// note:
/// Values provided here are defaults and can be overridden per usage.
/// Properties:
/// <ul>
///   <li>
///     <code>selectedBorderColor</code>: The border color used when an option is selected.
///     Defaults to <code>light: #2E72BF, dark: #158EE6</code>.
///   </li>
///   <li>
///     <code>unselectedBorderColor</code>: The border color used when an option is not selected.
///     Defaults to <code>light: #808080 alpha 0.2, dark: #CCCCCC alpha 0.2</code>.
///   </li>
///   <li>
///     <code>cellRadius</code>: The corner radius applied to each option cell, in points.
///     Defaults to <code>16</code>.
///   </li>
///   <li>
///     <code>cellBackgroundColor</code>: The background color for option cells.
///     Defaults to <code>light: #FFFFFF, dark: #0F0F0F</code>.
///   </li>
/// </ul>
/// Example:
/// <ul>
///   <li>
///     Increase <code>cellRadius</code> to match your app’s rounded corner style.
///   </li>
///   <li>
///     Set <code>selectedBorderColor</code> to your brand color to emphasize selection.
///   </li>
///   <li>
///     Adjust <code>cellBackgroundColor</code> to blend with your container background.
///   </li>
/// </ul>
/// Thread-safety:
/// <ul>
///   <li>
///     This type is a simple configuration object and is not thread-safe by design.
///     Configure it on the main thread or before passing it to UI components.
///   </li>
/// </ul>
/// Accessibility:
/// <ul>
///   <li>
///     Ensure chosen colors provide sufficient contrast, especially for
///     <code>selectedBorderColor</code> and <code>unselectedBorderColor</code>, to clearly indicate
///     selection state.
///   </li>
/// </ul>
SWIFT_CLASS("_TtC20AutopaySdkWithoutOCR21APDCCPaymentFormStyle")
@interface APDCCPaymentFormStyle : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// A customizable style container that defines the visual appearance
/// for dialog components presented by the SDK.
/// Use <code>APDialogStyle</code> to configure the dialog’s corner radius and background color
/// to better align the SDK dialogs with your app’s design system.
/// note:
/// Values provided here are defaults and can be overridden per usage.
/// Properties:
/// <ul>
///   <li>
///     <code>dialogRadius</code>: Corner radius applied to the dialog container, in points. Defaults to <code>16</code>.
///   </li>
///   <li>
///     <code>dialogBackgroundColor</code>: Background color of the dialog container (appearance-aware).
///     Defaults to <code>light: #F5F5F5, dark: #1F1F1F</code>.
///   </li>
/// </ul>
/// Example:
/// <ul>
///   <li>
///     Increase <code>dialogRadius</code> to create a softer, more rounded dialog.
///   </li>
///   <li>
///     Provide a custom <code>dialogBackgroundColor</code> to match brand or surface backgrounds.
///   </li>
/// </ul>
/// Thread-safety:
/// <ul>
///   <li>
///     This type is a simple configuration object and is not thread-safe by design.
///     Configure it on the main thread or before passing it to UI components.
///   </li>
/// </ul>
/// Accessibility:
/// <ul>
///   <li>
///     Ensure the chosen <code>dialogBackgroundColor</code> provides sufficient contrast with the dialog’s
///     text and controls, especially in both Light and Dark appearances.
///   </li>
/// </ul>
SWIFT_CLASS("_TtC20AutopaySdkWithoutOCR13APDialogStyle")
@interface APDialogStyle : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC20AutopaySdkWithoutOCR7APError")
@interface APError : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC20AutopaySdkWithoutOCR9APGateway")
@interface APGateway : NSObject
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC20AutopaySdkWithoutOCR26APGatewayBaseViewModelData")
@interface APGatewayBaseViewModelData : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC20AutopaySdkWithoutOCR26APGatewayListContainerView")
@interface APGatewayListContainerView : UIView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

/// A customizable style container that defines the visual appearance
/// for loading indicators/spinners used across the SDK.
/// Use <code>APLoaderStyle</code> to configure common aspects of loader visuals,
/// such as the default size for content loaders and the appearance-aware
/// color used for the spinner arc.
/// note:
/// Values provided here are defaults and can be overridden per usage.
/// Properties:
/// <ul>
///   <li>
///     <code>size</code>: The default diameter, in points, for content loaders. Defaults to <code>60</code>.
///   </li>
///   <li>
///     <code>color</code>: The appearance-aware color used for the spinner arc. Defaults to
///     <code>primaryColor</code> (light: #2E72BF, dark: #158EE6).
///   </li>
/// </ul>
/// Example:
/// <ul>
///   <li>
///     Increase <code>size</code> for prominent loading states.
///   </li>
///   <li>
///     Adjust <code>color</code> to match your brand or to ensure sufficient contrast.
///   </li>
/// </ul>
/// Thread-safety:
/// <ul>
///   <li>
///     This type is a simple configuration object and is not thread-safe by design.
///     Configure it on the main thread or before passing it to UI components.
///   </li>
/// </ul>
/// Accessibility:
/// <ul>
///   <li>
///     Ensure the chosen <code>color</code> provides sufficient contrast against the background,
///     especially when used with partial-opacity track strokes in loaders.
///   </li>
/// </ul>
SWIFT_CLASS("_TtC20AutopaySdkWithoutOCR13APLoaderStyle")
@interface APLoaderStyle : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC20AutopaySdkWithoutOCR5APLog")
@interface APLog : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC20AutopaySdkWithoutOCR7APParam")
@interface APParam : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// A customizable style container that defines the visual appearance and layout
/// for the payment method title/header component used within the SDK.
/// Use <code>APPaymentMethodTitleStyle</code> to configure how the payment method title is presented,
/// including its background color, icon tint, text typography, and corner radius.
/// note:
/// Values provided here are defaults and can be overridden per usage.
/// Properties:
/// <ul>
///   <li>
///     <code>backgroundColor</code>: Background color for the title container. Default: light <code>#FFFFFF</code>, dark <code>#0F0F0F</code>.
///   </li>
///   <li>
///     <code>iconColor</code>: Tint color used for the leading icon. Default: light <code>#000000</code>, dark <code>#FFFFFF</code>.
///   </li>
///   <li>
///     <code>textStyle</code>: Typography for the title text. Default font: System 16pt Regular.
///     Default color: light <code>#282828</code>, dark <code>#FAFAFA</code>.
///   </li>
///   <li>
///     <code>radius</code>: Corner radius applied to the title container, in points. Default: <code>16</code>.
///   </li>
/// </ul>
/// Example:
/// <ul>
///   <li>
///     Set a custom <code>backgroundColor</code> to align with your brand’s surfaces.
///   </li>
///   <li>
///     Adjust <code>iconColor</code> to ensure proper contrast against the background.
///   </li>
///   <li>
///     Provide a custom <code>textStyle</code> (font/weight/color) for hierarchy or branding needs.
///   </li>
///   <li>
///     Increase or decrease <code>radius</code> to match your app’s corner style.
///   </li>
/// </ul>
/// Thread-safety:
/// <ul>
///   <li>
///     This type is a simple configuration object and is not thread-safe by design.
///     Configure it on the main thread or before passing it to UI components.
///   </li>
/// </ul>
/// Accessibility:
/// <ul>
///   <li>
///     Ensure chosen colors provide sufficient contrast, especially for <code>iconColor</code> and <code>textStyle.color</code>,
///     to maintain readability and meet accessibility guidelines.
///   </li>
/// </ul>
SWIFT_CLASS("_TtC20AutopaySdkWithoutOCR25APPaymentMethodTitleStyle")
@interface APPaymentMethodTitleStyle : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// A customizable style container that defines the visual appearance and layout
/// for the payment summary section within the SDK.
/// Use <code>APPaymentSummaryStyle</code> to configure the background, border, dividers,
/// and corner radius of the payment summary container to match your brand and layout needs.
/// note:
/// Values provided here are defaults and can be overridden per usage.
/// Properties:
/// <ul>
///   <li>
///     <code>backgroundColor</code>: The background color of the summary container. Defaults to <code>light: #FFFFFF, dark: #0F0F0F</code>.
///   </li>
///   <li>
///     <code>borderColor</code>: The border color of the summary container. Defaults to <code>transparent</code>.
///   </li>
///   <li>
///     <code>dividerColor</code>: The color of dividers separating rows or sections. Defaults to <code>light: #808080 at 20% opacity, dark: #CCCCCC at 20% opacity</code>.
///   </li>
///   <li>
///     <code>borderWidth</code>: The thickness of the container border, in points. Defaults to <code>0</code>.
///   </li>
///   <li>
///     <code>dividerHeight</code>: The thickness of divider lines, in points. Defaults to <code>1</code>.
///   </li>
///   <li>
///     <code>radius</code>: The corner radius of the summary container, in points. Defaults to <code>16</code>.
///   </li>
/// </ul>
/// Example:
/// <ul>
///   <li>
///     Increase <code>borderWidth</code> to make the container outline visible.
///   </li>
///   <li>
///     Adjust <code>dividerHeight</code> for thicker or subtler separators.
///   </li>
///   <li>
///     Tweak <code>radius</code> to align with your app’s corner rounding.
///   </li>
///   <li>
///     Provide custom colors to ensure contrast and brand consistency.
///   </li>
/// </ul>
/// Thread-safety:
/// <ul>
///   <li>
///     This type is a simple configuration object and is not thread-safe by design.
///     Configure it on the main thread or before passing it to UI components.
///   </li>
/// </ul>
/// Accessibility:
/// <ul>
///   <li>
///     Ensure chosen colors provide sufficient contrast, especially for <code>dividerColor</code>
///     and <code>borderColor</code> against <code>backgroundColor</code>, to maintain readability.
///   </li>
/// </ul>
SWIFT_CLASS("_TtC20AutopaySdkWithoutOCR21APPaymentSummaryStyle")
@interface APPaymentSummaryStyle : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC20AutopaySdkWithoutOCR9APProduct")
@interface APProduct : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC20AutopaySdkWithoutOCR13APProductList")
@interface APProductList : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// A customizable style container that defines the visual appearance
/// of radio buttons within the SDK.
/// Use <code>APRadioButtonStyle</code> to configure the colors used to represent
/// checked and unchecked states of radio buttons, ensuring consistency
/// with your brand and accessibility needs.
/// note:
/// Values provided here are defaults and can be overridden per usage.
/// Properties:
/// <ul>
///   <li>
///     <code>checkedColor</code>: The color used when the radio button is selected (checked).
///     Defaults to <code>light: #2E72BF, dark: #158EE6</code>.
///   </li>
///   <li>
///     <code>uncheckedColor</code>: The color used when the radio button is not selected (unchecked).
///     Defaults to <code>light: #808080, dark: #CCCCCC</code>.
///   </li>
/// </ul>
/// Example:
/// <ul>
///   <li>
///     Set <code>checkedColor</code> to your brand color to highlight selection.
///   </li>
///   <li>
///     Adjust <code>uncheckedColor</code> for sufficient contrast in unselected state.
///   </li>
/// </ul>
/// Thread-safety:
/// <ul>
///   <li>
///     This type is a simple configuration object and is not thread-safe by design.
///     Configure it on the main thread or before passing it to UI components.
///   </li>
/// </ul>
/// Accessibility:
/// <ul>
///   <li>
///     Ensure chosen colors provide sufficient contrast between checked and
///     unchecked states to make selection visually distinguishable.
///   </li>
/// </ul>
SWIFT_CLASS("_TtC20AutopaySdkWithoutOCR18APRadioButtonStyle")
@interface APRadioButtonStyle : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC20AutopaySdkWithoutOCR8APResult")
@interface APResult : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// A central, observable style container that defines global typography,
/// colors, and component styles for the SDK.
/// Use <code>APStyleManager</code> to provide a single source of truth for theming across views.
/// Inject an instance into your SwiftUI hierarchy (e.g., via <code>EnvironmentObject</code>)
/// to enable live updates of styles at runtime. All exposed properties are published,
/// so changes propagate automatically to subscribed views.
/// note:
/// Values provided here are defaults and can be overridden per usage.
/// Properties:
/// <ul>
///   <li>
///     <code>typography</code>: Global typography tokens (fonts, weights, sizes, and default text color) used across the SDK.
///   </li>
///   <li>
///     <code>primaryButtonStyle</code>: Style preset for high-emphasis (primary) actions.
///   </li>
///   <li>
///     <code>secondaryButtonStyle</code>: Style preset for medium-emphasis (secondary) actions.
///   </li>
///   <li>
///     <code>tertiaryButtonStyle</code>: Style preset for low-emphasis (tertiary) actions.
///   </li>
///   <li>
///     <code>bankGridStyle</code>: Style for grids displaying selectable bank options.
///   </li>
///   <li>
///     <code>checkboxStyle</code>: Style for checkbox controls (checked/unchecked/error colors).
///   </li>
///   <li>
///     <code>dccPaymentFormStyle</code>: Style for Dynamic Currency Conversion (DCC) option cells.
///   </li>
///   <li>
///     <code>dialogStyle</code>: Style for modal dialog containers.
///   </li>
///   <li>
///     <code>loaderStyle</code>: Style for loading indicators/spinners.
///   </li>
///   <li>
///     <code>paymentMethodButtonStyle</code>: Style preset for buttons representing payment methods.
///   </li>
///   <li>
///     <code>paymentMethodTitleStyle</code>: Style for payment method title/header components.
///   </li>
///   <li>
///     <code>paymentSummaryStyle</code>: Style for payment summary containers and dividers.
///   </li>
///   <li>
///     <code>radioButtonStyle</code>: Style for radio button controls (checked/unchecked colors).
///   </li>
///   <li>
///     <code>switchStyle</code>: Style for switch/toggle controls (thumb/track/border colors).
///   </li>
///   <li>
///     <code>textInputStyle</code>: Style for text inputs (typography, borders, background, spacing).
///   </li>
///   <li>
///     <code>errorColor</code>: Global error color token used across components.
///   </li>
///   <li>
///     <code>footerIconsColor</code>: Color token used for iconography in footer or auxiliary areas.
///   </li>
/// </ul>
/// Example:
/// <ul>
///   <li>
///     Create a custom instance with brand styles and inject it at the root of any SDK View:
///     <code>@StateObject var sdkStyles = APStyleManager()</code>
///     <code>APGatewayListView().environmentObject(styles)</code>
///   </li>
///   <li>
///     Update properties (e.g., colors or text styles) at runtime to apply theme changes instantly.
///   </li>
/// </ul>
/// Thread-safety:
/// <ul>
///   <li>
///     This type coordinates UI styling and is intended to be read and updated on the main thread.
///   </li>
/// </ul>
/// Accessibility:
/// <ul>
///   <li>
///     Ensure chosen colors and text styles provide sufficient contrast and legibility in both Light and Dark appearances.
///   </li>
///   <li>
///     Prefer larger touch targets and readable font sizes where applicable.
///   </li>
/// </ul>
SWIFT_CLASS("_TtC20AutopaySdkWithoutOCR14APStyleManager")
@interface APStyleManager : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// A customizable style container that defines the visual colors for a switch
/// control within the SDK.
/// Use <code>APSwitchStyle</code> to configure the thumb, track, and border colors for both
/// checked (on) and unchecked (off) states of a switch/toggle component.
/// note:
/// Values provided here are defaults and can be overridden per usage.
/// Properties:
/// <ul>
///   <li>
///     <code>checkedThumbColor</code>: Color of the thumb when the control is on (checked).
///     Default: light #FFFFFF, dark #FAFAFA.
///   </li>
///   <li>
///     <code>uncheckedThumbColor</code>: Color of the thumb when the control is off (unchecked).
///     Default: light #808080, dark #CCCCCC.
///   </li>
///   <li>
///     <code>checkedTrackColor</code>: Color of the track when the control is on (checked).
///     Default: light #2E72BF, dark #158EE6.
///   </li>
///   <li>
///     <code>uncheckedTrackColor</code>: Color of the track when the control is off (unchecked).
///     Default: light #FFFFFF, dark #0F0F0F.
///   </li>
///   <li>
///     <code>checkedBorderColor</code>: Border color surrounding the control when it is on (checked).
///     Default: fully transparent.
///   </li>
///   <li>
///     <code>uncheckedBorderColor</code>: Border color surrounding the control when it is off (unchecked).
///     Default: light #808080, dark #CCCCCC.
///   </li>
/// </ul>
/// Example:
/// <ul>
///   <li>
///     Ensure <code>checkedTrackColor</code> provides strong contrast to clearly indicate the on state.
///   </li>
///   <li>
///     Match <code>uncheckedTrackColor</code> to your app’s background for a subtle off state.
///   </li>
///   <li>
///     Keep <code>checkedThumbColor</code> visually distinct from the track to improve affordance.
///   </li>
/// </ul>
/// Thread-safety:
/// <ul>
///   <li>
///     This type is a simple configuration object and is not thread-safe by design.
///     Configure it on the main thread or before passing it to UI components.
///   </li>
/// </ul>
/// Accessibility:
/// <ul>
///   <li>
///     Provide sufficient contrast between thumb and track in both states so users
///     can clearly perceive the control’s status.
///   </li>
/// </ul>
SWIFT_CLASS("_TtC20AutopaySdkWithoutOCR13APSwitchStyle")
@interface APSwitchStyle : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// A customizable style container that defines the visual appearance and layout
/// for text input fields within the SDK.
/// Use <code>APTextInputStyle</code> to configure typography and colors for input text, labels,
/// and error messages, as well as border colors for different states, background color,
/// trailing icon color, spacing between stacked inputs, stroke width, and corner radius.
/// note:
/// Values provided here are defaults and can be overridden per usage.
/// Properties:
/// <ul>
///   <li>
///     <code>inputTextStyle</code>: Typography and color for the user-entered text.
///     <ul>
///       <li>
///         Default font: System 16pt, Regular.
///       </li>
///       <li>
///         Default color: light #282828, dark #FAFAFA.
///       </li>
///     </ul>
///   </li>
///   <li>
///     <code>labelTextStyle</code>: Typography and color for the input label or placeholder.
///     <ul>
///       <li>
///         Default font: System 14pt, Regular.
///       </li>
///       <li>
///         Default color: light #282828, dark #FAFAFA.
///       </li>
///     </ul>
///   </li>
///   <li>
///     <code>errorTextStyle</code>: Typography and color for inline error messages.
///     <ul>
///       <li>
///         Default font: System 14pt, Regular.
///       </li>
///       <li>
///         Default color: light #BF4826, dark #E97655.
///       </li>
///     </ul>
///   </li>
///   <li>
///     <code>borderInactiveColor</code>: Border color when the input is not focused.
///     <ul>
///       <li>
///         Default: light #808080 at 40% opacity, dark #CCCCCC at 40% opacity.
///       </li>
///     </ul>
///   </li>
///   <li>
///     <code>borderActiveColor</code>: Border color when the input is focused/active.
///     <ul>
///       <li>
///         Default: light #2E72BF, dark #158EE6.
///       </li>
///     </ul>
///   </li>
///   <li>
///     <code>borderErrorColor</code>: Border color when the input is in an error state.
///     <ul>
///       <li>
///         Default: light #BF4826, dark #E97655.
///       </li>
///     </ul>
///   </li>
///   <li>
///     <code>backgroundColor</code>: Background color of the input field.
///     <ul>
///       <li>
///         Default: light #FFFFFF, dark #0F0F0F.
///       </li>
///     </ul>
///   </li>
///   <li>
///     <code>trailingIconsColor</code>: Color applied to trailing icons within the input..
///     <ul>
///       <li>
///         Default: light #282828, dark #FAFAFA.
///       </li>
///     </ul>
///   </li>
///   <li>
///     <code>spaceBetweenInputs</code>: Vertical spacing, in points, between stacked inputs. Default: 12.
///   </li>
///   <li>
///     <code>strokeWidth</code>: Border stroke width, in points. Default: 1.
///   </li>
///   <li>
///     <code>radius</code>: Corner radius of the input container, in points. Default: Infinity (pill/capsule).
///   </li>
/// </ul>
/// Example:
/// <ul>
///   <li>
///     Increase <code>strokeWidth</code> for stronger emphasis of the input boundary.
///   </li>
///   <li>
///     Set a finite <code>radius</code> (e.g., 12) to match your app’s corner style.
///   </li>
///   <li>
///     Adjust <code>borderActiveColor</code> and <code>borderErrorColor</code> to align with brand and error semantics.
///   </li>
///   <li>
///     Increase <code>spaceBetweenInputs</code> for forms with larger touch targets.
///   </li>
/// </ul>
/// Thread-safety:
/// <ul>
///   <li>
///     This type is a simple configuration object and is not thread-safe by design.
///     Configure it on the main thread or before passing it to UI components.
///   </li>
/// </ul>
/// Accessibility:
/// <ul>
///   <li>
///     Ensure chosen colors provide sufficient contrast in both Light and Dark appearances,
///     especially for <code>borderActiveColor</code>, <code>borderErrorColor</code>, and text colors.
///   </li>
///   <li>
///     Use readable font sizes and weights for labels and error messages.
///   </li>
/// </ul>
SWIFT_CLASS("_TtC20AutopaySdkWithoutOCR16APTextInputStyle")
@interface APTextInputStyle : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// A lightweight style container that defines the typographic appearance
/// for text elements within the SDK.
/// Use <code>APTextStyle</code> to configure the font and color used by text-based UI
/// components. Provide a <code>UIFont</code> to control size and weight, and an <code>APColor</code>
/// to supply appearance-aware (Light/Dark) text color.
/// note:
/// The <code>color</code> defaults to hex-based values when using the convenience
/// initializer: Light <code>#282828</code>, Dark <code>#FAFAFA</code>. The <code>font</code> has no default
/// and must be provided.
/// Properties:
/// <ul>
///   <li>
///     <code>font</code>: The font applied to the text. Required; no default.
///   </li>
///   <li>
///     <code>color</code>: The appearance-aware text color. Defaults to Light <code>#282828</code> / Dark <code>#FAFAFA</code>
///     when using the convenience initializer.
///   </li>
/// </ul>
/// Examples:
/// <ul>
///   <li>
///     Provide a custom font and rely on the default color:
///     <ul>
///       <li>
///         <code>APTextStyle(font: UIFont.systemFont(ofSize: 17, weight: .regular))</code>
///       </li>
///     </ul>
///   </li>
///   <li>
///     Provide both a custom font and color (hex-based):
///     <ul>
///       <li>
///         <code>APTextStyle(font: UIFont.preferredFont(forTextStyle: .body), color: APColor(light: Color(hex: "#000000"), dark: Color(hex: "#FFFFFF")))</code>
///       </li>
///     </ul>
///   </li>
///   <li>
///     Use different fonts for different components to establish hierarchy.
///   </li>
/// </ul>
/// Thread-safety:
/// <ul>
///   <li>
///     This type is a simple configuration object and is not thread-safe by design.
///     Configure it on the main thread or before passing it to UI components.
///   </li>
/// </ul>
/// Accessibility:
/// <ul>
///   <li>
///     Ensure chosen <code>font</code> sizes and weights meet readability guidelines.
///   </li>
///   <li>
///     Use colors with sufficient contrast in both Light and Dark appearances.
///   </li>
/// </ul>
SWIFT_CLASS("_TtC20AutopaySdkWithoutOCR11APTextStyle")
@interface APTextStyle : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC20AutopaySdkWithoutOCR13APTransaction")
@interface APTransaction : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC20AutopaySdkWithoutOCR17APTransactionData")
@interface APTransactionData : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC20AutopaySdkWithoutOCR19APTransactionStatus")
@interface APTransactionStatus : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// A customizable typography container that defines the default fonts and text color
/// used across SDK components.
/// Use <code>APTypography</code> to configure label and paragraph fonts as well as the default
/// foreground text color. These values act as defaults and can be overridden by
/// individual components when needed.
/// note:
/// Values provided here are defaults and can be overridden per usage.
/// Properties:
/// <ul>
///   <li>
///     <code>labelSmallFont</code>: Font used for small labels. Defaults to System, 12pt, Regular.
///   </li>
///   <li>
///     <code>labelMediumFont</code>: Font used for medium labels. Defaults to System, 14pt, Regular.
///   </li>
///   <li>
///     <code>labelLargeFont</code>: Font used for large labels. Defaults to System, 16pt, Regular.
///   </li>
///   <li>
///     <code>labelXLargeFont</code>: Font used for extra-large labels. Defaults to System, 18pt, Regular.
///   </li>
///   <li>
///     <code>labelSmallBoldFont</code>: Font used for small paragraph text. Defaults to System, 12pt, Medium.
///   </li>
///   <li>
///     <code>defaultTextColor</code>: Default text color (appearance-aware). Defaults to light: #282828, dark: #FAFAFA.
///   </li>
/// </ul>
/// Example:
/// <ul>
///   <li>
///     Increase <code>labelXLargeFont</code> for prominent headings.
///   </li>
///   <li>
///     Use a lighter weight for <code>labelLargeFont</code> to match your brand’s tone.
///   </li>
///   <li>
///     Adjust <code>defaultTextColor</code> to align with your brand palette (ensure contrast).
///   </li>
/// </ul>
/// Thread-safety:
/// <ul>
///   <li>
///     This type is a simple configuration object and is not thread-safe by design.
///     Configure it on the main thread or before passing it to UI components.
///   </li>
/// </ul>
/// Accessibility:
/// <ul>
///   <li>
///     Ensure chosen font sizes and weights provide sufficient readability.
///   </li>
///   <li>
///     Consider Dynamic Type and contrast when adjusting <code>defaultTextColor</code>.
///   </li>
/// </ul>
SWIFT_CLASS("_TtC20AutopaySdkWithoutOCR12APTypography")
@interface APTypography : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC20AutopaySdkWithoutOCR26APVisaGatewayContainerView")
@interface APVisaGatewayContainerView : UIView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

SWIFT_CLASS("_TtC20AutopaySdkWithoutOCR7Autopay")
@interface Autopay : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC20AutopaySdkWithoutOCR20WebViewContainerView")
@interface WebViewContainerView : UIView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

@class WKWebView;
@class WKNavigationResponse;
@class WKNavigationAction;
@class WKNavigation;
SWIFT_CLASS("_TtC20AutopaySdkWithoutOCR18WebViewCoordinator")
@interface WebViewCoordinator : NSObject <WKNavigationDelegate>
- (void)webView:(WKWebView * _Nonnull)_ decidePolicyForNavigationResponse:(WKNavigationResponse * _Nonnull)navigationResponse decisionHandler:(void (^ _Nonnull)(WKNavigationResponsePolicy))decisionHandler;
- (void)webView:(WKWebView * _Nonnull)_ decidePolicyForNavigationAction:(WKNavigationAction * _Nonnull)navigationAction decisionHandler:(void (^ _Nonnull)(WKNavigationActionPolicy))decisionHandler;
- (void)webView:(WKWebView * _Nonnull)webView didFailProvisionalNavigation:(WKNavigation * _Null_unspecified)_ withError:(NSError * _Nonnull)error;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class WKWebViewConfiguration;
@class WKWindowFeatures;
@class WKSecurityOrigin;
@class WKFrameInfo;
@interface WebViewCoordinator (SWIFT_EXTENSION(AutopaySdkWithoutOCR)) <WKUIDelegate>
- (WKWebView * _Nullable)webView:(WKWebView * _Nonnull)webView createWebViewWithConfiguration:(WKWebViewConfiguration * _Nonnull)configuration forNavigationAction:(WKNavigationAction * _Nonnull)_ windowFeatures:(WKWindowFeatures * _Nonnull)_ SWIFT_WARN_UNUSED_RESULT;
- (void)webViewDidClose:(WKWebView * _Nonnull)webView;
- (void)webView:(WKWebView * _Nonnull)webView requestMediaCapturePermissionForOrigin:(WKSecurityOrigin * _Nonnull)origin initiatedByFrame:(WKFrameInfo * _Nonnull)frame type:(WKMediaCaptureType)type decisionHandler:(void (^ _Nonnull)(WKPermissionDecision))decisionHandler;
@end

#endif // defined(__OBJC__)
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
